blog/urls.py
from django.urls import path

from . import views
from . import feeds

urlpatterns = [
  path('', views.IndexView.as_view(), name='blog-index'),
  path('rss/', feeds.BlogFeed(), name='blog-rss'),
  path('<slug>/', views.DetailView.as_view(), name='blog-detail'),
]

tsbarnes/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import include, path
from .views import index

urlpatterns = [
  path('', index, name='home'),
  path('blog/', include('blog.urls')),
  path('resume/', include('resume.urls')),
  path('portfolio/', include('portfolio.urls')),
  path('admin_tools/', include('admin_tools.urls')),
  path('admin/', admin.site.urls),
  path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
  urlpatterns += [
    path('media/<path>', serve, {
      'document_root': settings.MEDIA_ROOT,
    }),
  ]

blog/models.py
from django.db import models
from django.utils import timezone

class Article(models.Model):
  slug = models.SlugField(blank=False)
  title = models.CharField(max_length=255, blank=False)
  subtitle = models.CharField(max_length=255, blank=True)
  header_image = models.ImageField(blank=True)
  short = models.TextField(blank=False)
  text = models.TextField(blank=False)
  date = models.DateField(default=timezone.now)
  created_at=models.DateTimeField(auto_now_add=True)
  updated_at=models.DateTimeField(auto_now=True)
  published = models.BooleanField(default=False)

  class Meta:
    ordering = ['-date']

  def __unicode__(self):
    return self.title
  
  def __str__(self):
    return self.__unicode__()

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Article


class IndexView(generic.ListView):
  model = Article
  template_name = 'blog/index.html'

  def get_queryset(self):
    queryset = Article.objects.filter(published=True)
    return queryset

class DetailView(generic.DetailView):
  model = Article
  template_name = 'blog/detail.html'

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="card m-2">
    {% if article.header_image %}
      <img class="card-img-top" src="{{ article.header_image.url }}">
    {% endif %}
    <div class="card-body">
      <div class="d-flex w-100 justify-content-between">
        <h3 class="card-title">{{ article.title }}</h3>
        <small>{{ article.date }}</small>
      </div>
      <h5 class="card-subtitle mb-2 text-muted">{{ article.subtitle }}</h5>
      <p>{{ article.text|safe }}</h1>
    </div>
  </div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  <div class="card">
    <h1 class="card-header">Articles</h1>
    <div class="card-body">
      {% if article_list %}
        <div class="row">
          {% for article in article_list %}
            <div class="col-4">
              <div class="card">
                {% if article.header_image %}
                  <img class="card-img" src="{{ article.header_image.url }}">
                {% endif %}
                <div class="card-body">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <small>{{ article.date }}</small>
                  </div>
                  <p class="card-text">
                    {{ article.short|safe }}
                  </p>
                  <a class="btn btn-primary" href="{% url 'blog-detail' article.slug %}">Read more...</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% else %}
        <div class="card">
          <div class="card-body">
            <p class="card-text">No articles are available.</p>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}